name: Run tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run lint
      run: ./gradlew ktlintCheck

    - name: Run detekt
      run: ./gradlew detekt

    - name: Generate kover coverage report
      run: ./gradlew koverMergedXmlReport

    - name: Kotlinx Kover Report
      uses: mi-kas/kover-report@v1
      with:
        path: ${{ github.workspace }}/build/reports/kover/merged/xml/report.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Code Coverage
        update-comment: true
        # min-coverage-overall: 80
        min-coverage-changed-files: 80

  steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{ github.workspace }}/build/reports/kover/merged/xml/report.xml
        name: codecov
        fail_ci_if_error: false
        verbose: true
